### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by nmeum** [dubiousjim/dcron#14]
The C source files only state the following:

```
May be distributed under the GNU General Public License
```

However, it is not specified which version of the GPL is being used. ln addition to that it would be neat if you could add a license file containing the entire license text to the repository.

**Comment by ffontaine** [comment]
It seems to have been fixed by https://github.com/dubiousjim/dcron/commit/1ba33c3325df48de46263276a43ed76cf9d81518
