### ISSUE TITLE
Allow use of nano

### ISSUE THREAD

**Issue by Justinzobel** [dubiousjim/dcron#5]
Add option to use nano instead of vi for editor.

**Comment by dubiousjim** [comment]
Have your environment variable EDITOR set to a string that resolves to nano using your PATH. Usually `EDITOR=nano` will be enough.

**Comment by Justinzobel** [comment]
I have that in my .bashrc and I still get pushed into vim when I do sudo 
crontab -e

**Comment by dubiousjim** [comment]
OK, that's because the `EDITOR` variable is getting stripped by `sudo`. There are tweaks you can make to your `/etc/sudoers` file to prevent it. But the easiest way is to do this:

    $ sudo -s
    # EDITOR=nano crontab -e

or this:

    $ sudo env EDITOR=nano crontab -e

**Comment by Justinzobel** [comment]
Thanks that worked!
